source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
target 'WisdomLife' do
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'DZNEmptyDataSet'
pod 'SAMKeychain'
pod 'YYModel'
pod 'MBProgressHUD'
end
